package net.maple.grecablocks.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.maple.grecablocks.block.ModBlocks;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.BlockTags;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagProvider extends FabricTagProvider.BlockTagProvider{
    public ModBlockTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
        super(output, registriesFuture);
    }

    @Override
    protected void configure(RegistryWrapper.WrapperLookup wrapperLookup) {
        getOrCreateTagBuilder(BlockTags.PICKAXE_MINEABLE)
        // stone bricks engraved
                .add(ModBlocks.STONE_BRICKS_AMETHYST_BANDS).add(ModBlocks.STONE_BRICKS_AMETHYST_CHEVRON).add(ModBlocks.STONE_BRICKS_AMETHYST_WAVES)
                .add(ModBlocks.STONE_BRICKS_DIAMOND_BANDS).add(ModBlocks.STONE_BRICKS_DIAMOND_CHEVRON).add(ModBlocks.STONE_BRICKS_DIAMOND_WAVES)
                .add(ModBlocks.STONE_BRICKS_EMERALD_BANDS).add(ModBlocks.STONE_BRICKS_EMERALD_CHEVRON).add(ModBlocks.STONE_BRICKS_EMERALD_WAVES)
                .add(ModBlocks.STONE_BRICKS_GOLD_BANDS).add(ModBlocks.STONE_BRICKS_GOLD_CHEVRON).add(ModBlocks.STONE_BRICKS_GOLD_WAVES)
                .add(ModBlocks.STONE_BRICKS_IRON_BANDS).add(ModBlocks.STONE_BRICKS_IRON_CHEVRON).add(ModBlocks.STONE_BRICKS_IRON_WAVES)

                .add(ModBlocks.STONE_BRICKS_COPPER_BANDS).add(ModBlocks.STONE_BRICKS_COPPER_CHEVRON).add(ModBlocks.STONE_BRICKS_COPPER_WAVES)
                .add(ModBlocks.STONE_BRICKS_EXPOSED_COPPER_BANDS).add(ModBlocks.STONE_BRICKS_EXPOSED_COPPER_CHEVRON).add(ModBlocks.STONE_BRICKS_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.STONE_BRICKS_WEATHERED_COPPER_BANDS).add(ModBlocks.STONE_BRICKS_WEATHERED_COPPER_CHEVRON).add(ModBlocks.STONE_BRICKS_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.STONE_BRICKS_OXIDIZED_COPPER_BANDS).add(ModBlocks.STONE_BRICKS_OXIDIZED_COPPER_CHEVRON).add(ModBlocks.STONE_BRICKS_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.STONE_BRICKS_WAXED_COPPER_BANDS).add(ModBlocks.STONE_BRICKS_WAXED_COPPER_CHEVRON).add(ModBlocks.STONE_BRICKS_WAXED_COPPER_WAVES)
                .add(ModBlocks.STONE_BRICKS_WAXED_EXPOSED_COPPER_BANDS).add(ModBlocks.STONE_BRICKS_WAXED_EXPOSED_COPPER_CHEVRON).add(ModBlocks.STONE_BRICKS_WAXED_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.STONE_BRICKS_WAXED_WEATHERED_COPPER_BANDS).add(ModBlocks.STONE_BRICKS_WAXED_WEATHERED_COPPER_CHEVRON).add(ModBlocks.STONE_BRICKS_WAXED_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.STONE_BRICKS_WAXED_OXIDIZED_COPPER_BANDS).add(ModBlocks.STONE_BRICKS_WAXED_OXIDIZED_COPPER_CHEVRON).add(ModBlocks.STONE_BRICKS_WAXED_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.STONE_BRICKS_LAPIS_BANDS).add(ModBlocks.STONE_BRICKS_LAPIS_CHEVRON).add(ModBlocks.STONE_BRICKS_LAPIS_WAVES)
                .add(ModBlocks.STONE_BRICKS_REDSTONE_BANDS).add(ModBlocks.STONE_BRICKS_REDSTONE_CHEVRON).add(ModBlocks.STONE_BRICKS_REDSTONE_WAVES)
                .add(ModBlocks.STONE_BRICKS_QUARTZ_BANDS).add(ModBlocks.STONE_BRICKS_QUARTZ_CHEVRON).add(ModBlocks.STONE_BRICKS_QUARTZ_WAVES)
// deepslate bricks engraved

                .add(ModBlocks.DEEPSLATE_BRICKS_AMETHYST_BANDS).add(ModBlocks.DEEPSLATE_BRICKS_AMETHYST_CHEVRON).add(ModBlocks.DEEPSLATE_BRICKS_AMETHYST_WAVES)
                .add(ModBlocks.DEEPSLATE_BRICKS_DIAMOND_BANDS).add(ModBlocks.DEEPSLATE_BRICKS_DIAMOND_CHEVRON).add(ModBlocks.DEEPSLATE_BRICKS_DIAMOND_WAVES)
                .add(ModBlocks.DEEPSLATE_BRICKS_EMERALD_BANDS).add(ModBlocks.DEEPSLATE_BRICKS_EMERALD_CHEVRON).add(ModBlocks.DEEPSLATE_BRICKS_EMERALD_WAVES)
                .add(ModBlocks.DEEPSLATE_BRICKS_GOLD_BANDS).add(ModBlocks.DEEPSLATE_BRICKS_GOLD_CHEVRON).add(ModBlocks.DEEPSLATE_BRICKS_GOLD_WAVES)
                .add(ModBlocks.DEEPSLATE_BRICKS_IRON_BANDS).add(ModBlocks.DEEPSLATE_BRICKS_IRON_CHEVRON).add(ModBlocks.DEEPSLATE_BRICKS_IRON_WAVES)

                .add(ModBlocks.DEEPSLATE_BRICKS_COPPER_BANDS).add(ModBlocks.DEEPSLATE_BRICKS_COPPER_CHEVRON).add(ModBlocks.DEEPSLATE_BRICKS_COPPER_WAVES)
                .add(ModBlocks.DEEPSLATE_BRICKS_EXPOSED_COPPER_BANDS).add(ModBlocks.DEEPSLATE_BRICKS_EXPOSED_COPPER_CHEVRON).add(ModBlocks.DEEPSLATE_BRICKS_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.DEEPSLATE_BRICKS_WEATHERED_COPPER_BANDS).add(ModBlocks.DEEPSLATE_BRICKS_WEATHERED_COPPER_CHEVRON).add(ModBlocks.DEEPSLATE_BRICKS_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.DEEPSLATE_BRICKS_OXIDIZED_COPPER_BANDS).add(ModBlocks.DEEPSLATE_BRICKS_OXIDIZED_COPPER_CHEVRON).add(ModBlocks.DEEPSLATE_BRICKS_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.DEEPSLATE_BRICKS_WAXED_COPPER_BANDS).add(ModBlocks.DEEPSLATE_BRICKS_WAXED_COPPER_CHEVRON).add(ModBlocks.DEEPSLATE_BRICKS_WAXED_COPPER_WAVES)
                .add(ModBlocks.DEEPSLATE_BRICKS_WAXED_EXPOSED_COPPER_BANDS).add(ModBlocks.DEEPSLATE_BRICKS_WAXED_EXPOSED_COPPER_CHEVRON).add(ModBlocks.DEEPSLATE_BRICKS_WAXED_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.DEEPSLATE_BRICKS_WAXED_WEATHERED_COPPER_BANDS).add(ModBlocks.DEEPSLATE_BRICKS_WAXED_WEATHERED_COPPER_CHEVRON).add(ModBlocks.DEEPSLATE_BRICKS_WAXED_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.DEEPSLATE_BRICKS_WAXED_OXIDIZED_COPPER_BANDS).add(ModBlocks.DEEPSLATE_BRICKS_WAXED_OXIDIZED_COPPER_CHEVRON).add(ModBlocks.DEEPSLATE_BRICKS_WAXED_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.DEEPSLATE_BRICKS_LAPIS_BANDS).add(ModBlocks.DEEPSLATE_BRICKS_LAPIS_CHEVRON).add(ModBlocks.DEEPSLATE_BRICKS_LAPIS_WAVES)
                .add(ModBlocks.DEEPSLATE_BRICKS_REDSTONE_BANDS).add(ModBlocks.DEEPSLATE_BRICKS_REDSTONE_CHEVRON).add(ModBlocks.DEEPSLATE_BRICKS_REDSTONE_WAVES)
                .add(ModBlocks.DEEPSLATE_BRICKS_QUARTZ_BANDS).add(ModBlocks.DEEPSLATE_BRICKS_QUARTZ_CHEVRON).add(ModBlocks.DEEPSLATE_BRICKS_QUARTZ_WAVES)

        // mud bricks engraved
                .add(ModBlocks.MUD_BRICKS_GOLD_BANDS).add(ModBlocks.MUD_BRICKS_GOLD_CHEVRON).add(ModBlocks.MUD_BRICKS_GOLD_WAVES)
                .add(ModBlocks.MUD_BRICKS_IRON_BANDS).add(ModBlocks.MUD_BRICKS_IRON_CHEVRON).add(ModBlocks.MUD_BRICKS_IRON_WAVES)

                .add(ModBlocks.MUD_BRICKS_COPPER_BANDS).add(ModBlocks.MUD_BRICKS_COPPER_CHEVRON).add(ModBlocks.MUD_BRICKS_COPPER_WAVES)
                .add(ModBlocks.MUD_BRICKS_EXPOSED_COPPER_BANDS).add(ModBlocks.MUD_BRICKS_EXPOSED_COPPER_CHEVRON).add(ModBlocks.MUD_BRICKS_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.MUD_BRICKS_WEATHERED_COPPER_BANDS).add(ModBlocks.MUD_BRICKS_WEATHERED_COPPER_CHEVRON).add(ModBlocks.MUD_BRICKS_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.MUD_BRICKS_OXIDIZED_COPPER_BANDS).add(ModBlocks.MUD_BRICKS_OXIDIZED_COPPER_CHEVRON).add(ModBlocks.MUD_BRICKS_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.MUD_BRICKS_WAXED_COPPER_BANDS).add(ModBlocks.MUD_BRICKS_WAXED_COPPER_CHEVRON).add(ModBlocks.MUD_BRICKS_WAXED_COPPER_WAVES)
                .add(ModBlocks.MUD_BRICKS_WAXED_EXPOSED_COPPER_BANDS).add(ModBlocks.MUD_BRICKS_WAXED_EXPOSED_COPPER_CHEVRON).add(ModBlocks.MUD_BRICKS_WAXED_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.MUD_BRICKS_WAXED_WEATHERED_COPPER_BANDS).add(ModBlocks.MUD_BRICKS_WAXED_WEATHERED_COPPER_CHEVRON).add(ModBlocks.MUD_BRICKS_WAXED_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.MUD_BRICKS_WAXED_OXIDIZED_COPPER_BANDS).add(ModBlocks.MUD_BRICKS_WAXED_OXIDIZED_COPPER_CHEVRON).add(ModBlocks.MUD_BRICKS_WAXED_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.MUD_BRICKS_LAPIS_BANDS).add(ModBlocks.MUD_BRICKS_LAPIS_CHEVRON).add(ModBlocks.MUD_BRICKS_LAPIS_WAVES)
                .add(ModBlocks.MUD_BRICKS_REDSTONE_BANDS).add(ModBlocks.MUD_BRICKS_REDSTONE_CHEVRON).add(ModBlocks.MUD_BRICKS_REDSTONE_WAVES)
                .add(ModBlocks.MUD_BRICKS_QUARTZ_BANDS).add(ModBlocks.MUD_BRICKS_QUARTZ_CHEVRON).add(ModBlocks.MUD_BRICKS_QUARTZ_WAVES)

        // prismarine bricks engraved
                .add(ModBlocks.PRISMARINE_BRICKS_AMETHYST_BANDS).add(ModBlocks.PRISMARINE_BRICKS_AMETHYST_CHEVRON).add(ModBlocks.PRISMARINE_BRICKS_AMETHYST_WAVES)
                .add(ModBlocks.PRISMARINE_BRICKS_DIAMOND_BANDS).add(ModBlocks.PRISMARINE_BRICKS_DIAMOND_CHEVRON).add(ModBlocks.PRISMARINE_BRICKS_DIAMOND_WAVES)
                .add(ModBlocks.PRISMARINE_BRICKS_EMERALD_BANDS).add(ModBlocks.PRISMARINE_BRICKS_EMERALD_CHEVRON).add(ModBlocks.PRISMARINE_BRICKS_EMERALD_WAVES)
                .add(ModBlocks.PRISMARINE_BRICKS_GOLD_BANDS).add(ModBlocks.PRISMARINE_BRICKS_GOLD_CHEVRON).add(ModBlocks.PRISMARINE_BRICKS_GOLD_WAVES)
                .add(ModBlocks.PRISMARINE_BRICKS_IRON_BANDS).add(ModBlocks.PRISMARINE_BRICKS_IRON_CHEVRON).add(ModBlocks.PRISMARINE_BRICKS_IRON_WAVES)

                .add(ModBlocks.PRISMARINE_BRICKS_COPPER_BANDS).add(ModBlocks.PRISMARINE_BRICKS_COPPER_CHEVRON).add(ModBlocks.PRISMARINE_BRICKS_COPPER_WAVES)
                .add(ModBlocks.PRISMARINE_BRICKS_EXPOSED_COPPER_BANDS).add(ModBlocks.PRISMARINE_BRICKS_EXPOSED_COPPER_CHEVRON).add(ModBlocks.PRISMARINE_BRICKS_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.PRISMARINE_BRICKS_WEATHERED_COPPER_BANDS).add(ModBlocks.PRISMARINE_BRICKS_WEATHERED_COPPER_CHEVRON).add(ModBlocks.PRISMARINE_BRICKS_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.PRISMARINE_BRICKS_OXIDIZED_COPPER_BANDS).add(ModBlocks.PRISMARINE_BRICKS_OXIDIZED_COPPER_CHEVRON).add(ModBlocks.PRISMARINE_BRICKS_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.PRISMARINE_BRICKS_WAXED_COPPER_BANDS).add(ModBlocks.PRISMARINE_BRICKS_WAXED_COPPER_CHEVRON).add(ModBlocks.PRISMARINE_BRICKS_WAXED_COPPER_WAVES)
                .add(ModBlocks.PRISMARINE_BRICKS_WAXED_EXPOSED_COPPER_BANDS).add(ModBlocks.PRISMARINE_BRICKS_WAXED_EXPOSED_COPPER_CHEVRON).add(ModBlocks.PRISMARINE_BRICKS_WAXED_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.PRISMARINE_BRICKS_WAXED_WEATHERED_COPPER_BANDS).add(ModBlocks.PRISMARINE_BRICKS_WAXED_WEATHERED_COPPER_CHEVRON).add(ModBlocks.PRISMARINE_BRICKS_WAXED_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.PRISMARINE_BRICKS_WAXED_OXIDIZED_COPPER_BANDS).add(ModBlocks.PRISMARINE_BRICKS_WAXED_OXIDIZED_COPPER_CHEVRON).add(ModBlocks.PRISMARINE_BRICKS_WAXED_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.PRISMARINE_BRICKS_LAPIS_BANDS).add(ModBlocks.PRISMARINE_BRICKS_LAPIS_CHEVRON).add(ModBlocks.PRISMARINE_BRICKS_LAPIS_WAVES)
                .add(ModBlocks.PRISMARINE_BRICKS_REDSTONE_BANDS).add(ModBlocks.PRISMARINE_BRICKS_REDSTONE_CHEVRON).add(ModBlocks.PRISMARINE_BRICKS_REDSTONE_WAVES)
                .add(ModBlocks.PRISMARINE_BRICKS_QUARTZ_BANDS).add(ModBlocks.PRISMARINE_BRICKS_QUARTZ_CHEVRON).add(ModBlocks.PRISMARINE_BRICKS_QUARTZ_WAVES)

                // sandstone bricks engraved
                .add(ModBlocks.SANDSTONE_GOLD_BANDS).add(ModBlocks.SANDSTONE_GOLD_CHEVRON).add(ModBlocks.SANDSTONE_GOLD_WAVES)
                .add(ModBlocks.SANDSTONE_IRON_BANDS).add(ModBlocks.SANDSTONE_IRON_CHEVRON).add(ModBlocks.SANDSTONE_IRON_WAVES)

                .add(ModBlocks.SANDSTONE_COPPER_BANDS).add(ModBlocks.SANDSTONE_COPPER_CHEVRON).add(ModBlocks.SANDSTONE_COPPER_WAVES)
                .add(ModBlocks.SANDSTONE_EXPOSED_COPPER_BANDS).add(ModBlocks.SANDSTONE_EXPOSED_COPPER_CHEVRON).add(ModBlocks.SANDSTONE_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.SANDSTONE_WEATHERED_COPPER_BANDS).add(ModBlocks.SANDSTONE_WEATHERED_COPPER_CHEVRON).add(ModBlocks.SANDSTONE_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.SANDSTONE_OXIDIZED_COPPER_BANDS).add(ModBlocks.SANDSTONE_OXIDIZED_COPPER_CHEVRON).add(ModBlocks.SANDSTONE_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.SANDSTONE_WAXED_COPPER_BANDS).add(ModBlocks.SANDSTONE_WAXED_COPPER_CHEVRON).add(ModBlocks.SANDSTONE_WAXED_COPPER_WAVES)
                .add(ModBlocks.SANDSTONE_WAXED_EXPOSED_COPPER_BANDS).add(ModBlocks.SANDSTONE_WAXED_EXPOSED_COPPER_CHEVRON).add(ModBlocks.SANDSTONE_WAXED_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.SANDSTONE_WAXED_WEATHERED_COPPER_BANDS).add(ModBlocks.SANDSTONE_WAXED_WEATHERED_COPPER_CHEVRON).add(ModBlocks.SANDSTONE_WAXED_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.SANDSTONE_WAXED_OXIDIZED_COPPER_BANDS).add(ModBlocks.SANDSTONE_WAXED_OXIDIZED_COPPER_CHEVRON).add(ModBlocks.SANDSTONE_WAXED_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.SANDSTONE_LAPIS_BANDS).add(ModBlocks.SANDSTONE_LAPIS_CHEVRON).add(ModBlocks.SANDSTONE_LAPIS_WAVES)
                .add(ModBlocks.SANDSTONE_REDSTONE_BANDS).add(ModBlocks.SANDSTONE_REDSTONE_CHEVRON).add(ModBlocks.SANDSTONE_REDSTONE_WAVES)
                .add(ModBlocks.SANDSTONE_QUARTZ_BANDS).add(ModBlocks.SANDSTONE_QUARTZ_CHEVRON).add(ModBlocks.SANDSTONE_QUARTZ_WAVES)

        // red sandstone bricks engraved
                .add(ModBlocks.RED_SANDSTONE_GOLD_BANDS).add(ModBlocks.RED_SANDSTONE_GOLD_CHEVRON).add(ModBlocks.RED_SANDSTONE_GOLD_WAVES)
                .add(ModBlocks.RED_SANDSTONE_IRON_BANDS).add(ModBlocks.RED_SANDSTONE_IRON_CHEVRON).add(ModBlocks.RED_SANDSTONE_IRON_WAVES)

                .add(ModBlocks.RED_SANDSTONE_COPPER_BANDS).add(ModBlocks.RED_SANDSTONE_COPPER_CHEVRON).add(ModBlocks.RED_SANDSTONE_COPPER_WAVES)
                .add(ModBlocks.RED_SANDSTONE_EXPOSED_COPPER_BANDS).add(ModBlocks.RED_SANDSTONE_EXPOSED_COPPER_CHEVRON).add(ModBlocks.RED_SANDSTONE_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.RED_SANDSTONE_WEATHERED_COPPER_BANDS).add(ModBlocks.RED_SANDSTONE_WEATHERED_COPPER_CHEVRON).add(ModBlocks.RED_SANDSTONE_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.RED_SANDSTONE_OXIDIZED_COPPER_BANDS).add(ModBlocks.RED_SANDSTONE_OXIDIZED_COPPER_CHEVRON).add(ModBlocks.RED_SANDSTONE_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.RED_SANDSTONE_WAXED_COPPER_BANDS).add(ModBlocks.RED_SANDSTONE_WAXED_COPPER_CHEVRON).add(ModBlocks.RED_SANDSTONE_WAXED_COPPER_WAVES)
                .add(ModBlocks.RED_SANDSTONE_WAXED_EXPOSED_COPPER_BANDS).add(ModBlocks.RED_SANDSTONE_WAXED_EXPOSED_COPPER_CHEVRON).add(ModBlocks.RED_SANDSTONE_WAXED_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.RED_SANDSTONE_WAXED_WEATHERED_COPPER_BANDS).add(ModBlocks.RED_SANDSTONE_WAXED_WEATHERED_COPPER_CHEVRON).add(ModBlocks.RED_SANDSTONE_WAXED_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.RED_SANDSTONE_WAXED_OXIDIZED_COPPER_BANDS).add(ModBlocks.RED_SANDSTONE_WAXED_OXIDIZED_COPPER_CHEVRON).add(ModBlocks.RED_SANDSTONE_WAXED_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.RED_SANDSTONE_LAPIS_BANDS).add(ModBlocks.RED_SANDSTONE_LAPIS_CHEVRON).add(ModBlocks.RED_SANDSTONE_LAPIS_WAVES)
                .add(ModBlocks.RED_SANDSTONE_REDSTONE_BANDS).add(ModBlocks.RED_SANDSTONE_REDSTONE_CHEVRON).add(ModBlocks.RED_SANDSTONE_REDSTONE_WAVES)
                .add(ModBlocks.RED_SANDSTONE_QUARTZ_BANDS).add(ModBlocks.RED_SANDSTONE_QUARTZ_CHEVRON).add(ModBlocks.RED_SANDSTONE_QUARTZ_WAVES)

        // cut copper engraved
                .add(ModBlocks.CUT_COPPER_AMETHYST_BANDS).add(ModBlocks.CUT_COPPER_AMETHYST_CHEVRON).add(ModBlocks.CUT_COPPER_AMETHYST_WAVES)
                .add(ModBlocks.CUT_COPPER_DIAMOND_BANDS).add(ModBlocks.CUT_COPPER_DIAMOND_CHEVRON).add(ModBlocks.CUT_COPPER_DIAMOND_WAVES)
                .add(ModBlocks.CUT_COPPER_EMERALD_BANDS).add(ModBlocks.CUT_COPPER_EMERALD_CHEVRON).add(ModBlocks.CUT_COPPER_EMERALD_WAVES)
                .add(ModBlocks.CUT_COPPER_GOLD_BANDS).add(ModBlocks.CUT_COPPER_GOLD_CHEVRON).add(ModBlocks.CUT_COPPER_GOLD_WAVES)
                .add(ModBlocks.CUT_COPPER_IRON_BANDS).add(ModBlocks.CUT_COPPER_IRON_CHEVRON).add(ModBlocks.CUT_COPPER_IRON_WAVES)

                .add(ModBlocks.WAXED_CUT_COPPER_AMETHYST_BANDS).add(ModBlocks.WAXED_CUT_COPPER_AMETHYST_CHEVRON).add(ModBlocks.WAXED_CUT_COPPER_AMETHYST_WAVES)
                .add(ModBlocks.WAXED_CUT_COPPER_DIAMOND_BANDS).add(ModBlocks.WAXED_CUT_COPPER_DIAMOND_CHEVRON).add(ModBlocks.WAXED_CUT_COPPER_DIAMOND_WAVES)
                .add(ModBlocks.WAXED_CUT_COPPER_EMERALD_BANDS).add(ModBlocks.WAXED_CUT_COPPER_EMERALD_CHEVRON).add(ModBlocks.WAXED_CUT_COPPER_EMERALD_WAVES)
                .add(ModBlocks.WAXED_CUT_COPPER_GOLD_BANDS).add(ModBlocks.WAXED_CUT_COPPER_GOLD_CHEVRON).add(ModBlocks.WAXED_CUT_COPPER_GOLD_WAVES)
                .add(ModBlocks.WAXED_CUT_COPPER_IRON_BANDS).add(ModBlocks.WAXED_CUT_COPPER_IRON_CHEVRON).add(ModBlocks.WAXED_CUT_COPPER_IRON_WAVES)

        // exposed cut copper engraved
                .add(ModBlocks.EXPOSED_CUT_COPPER_AMETHYST_BANDS).add(ModBlocks.EXPOSED_CUT_COPPER_AMETHYST_CHEVRON).add(ModBlocks.EXPOSED_CUT_COPPER_AMETHYST_WAVES)
                .add(ModBlocks.EXPOSED_CUT_COPPER_DIAMOND_BANDS).add(ModBlocks.EXPOSED_CUT_COPPER_DIAMOND_CHEVRON).add(ModBlocks.EXPOSED_CUT_COPPER_DIAMOND_WAVES)
                .add(ModBlocks.EXPOSED_CUT_COPPER_EMERALD_BANDS).add(ModBlocks.EXPOSED_CUT_COPPER_EMERALD_CHEVRON).add(ModBlocks.EXPOSED_CUT_COPPER_EMERALD_WAVES)
                .add(ModBlocks.EXPOSED_CUT_COPPER_GOLD_BANDS).add(ModBlocks.EXPOSED_CUT_COPPER_GOLD_CHEVRON).add(ModBlocks.EXPOSED_CUT_COPPER_GOLD_WAVES)
                .add(ModBlocks.EXPOSED_CUT_COPPER_IRON_BANDS).add(ModBlocks.EXPOSED_CUT_COPPER_IRON_CHEVRON).add(ModBlocks.EXPOSED_CUT_COPPER_IRON_WAVES)

                .add(ModBlocks.WAXED_EXPOSED_CUT_COPPER_AMETHYST_BANDS).add(ModBlocks.WAXED_EXPOSED_CUT_COPPER_AMETHYST_CHEVRON).add(ModBlocks.WAXED_EXPOSED_CUT_COPPER_AMETHYST_WAVES)
                .add(ModBlocks.WAXED_EXPOSED_CUT_COPPER_DIAMOND_BANDS).add(ModBlocks.WAXED_EXPOSED_CUT_COPPER_DIAMOND_CHEVRON).add(ModBlocks.WAXED_EXPOSED_CUT_COPPER_DIAMOND_WAVES)
                .add(ModBlocks.WAXED_EXPOSED_CUT_COPPER_EMERALD_BANDS).add(ModBlocks.WAXED_EXPOSED_CUT_COPPER_EMERALD_CHEVRON).add(ModBlocks.WAXED_EXPOSED_CUT_COPPER_EMERALD_WAVES)
                .add(ModBlocks.WAXED_EXPOSED_CUT_COPPER_GOLD_BANDS).add(ModBlocks.WAXED_EXPOSED_CUT_COPPER_GOLD_CHEVRON).add(ModBlocks.WAXED_EXPOSED_CUT_COPPER_GOLD_WAVES)
                .add(ModBlocks.WAXED_EXPOSED_CUT_COPPER_IRON_BANDS).add(ModBlocks.WAXED_EXPOSED_CUT_COPPER_IRON_CHEVRON).add(ModBlocks.WAXED_EXPOSED_CUT_COPPER_IRON_WAVES)

        // weathered cut copper engraved
                .add(ModBlocks.WEATHERED_CUT_COPPER_AMETHYST_BANDS).add(ModBlocks.WEATHERED_CUT_COPPER_AMETHYST_CHEVRON).add(ModBlocks.WEATHERED_CUT_COPPER_AMETHYST_WAVES)
                .add(ModBlocks.WEATHERED_CUT_COPPER_DIAMOND_BANDS).add(ModBlocks.WEATHERED_CUT_COPPER_DIAMOND_CHEVRON).add(ModBlocks.WEATHERED_CUT_COPPER_DIAMOND_WAVES)
                .add(ModBlocks.WEATHERED_CUT_COPPER_EMERALD_BANDS).add(ModBlocks.WEATHERED_CUT_COPPER_EMERALD_CHEVRON).add(ModBlocks.WEATHERED_CUT_COPPER_EMERALD_WAVES)
                .add(ModBlocks.WEATHERED_CUT_COPPER_GOLD_BANDS).add(ModBlocks.WEATHERED_CUT_COPPER_GOLD_CHEVRON).add(ModBlocks.WEATHERED_CUT_COPPER_GOLD_WAVES)
                .add(ModBlocks.WEATHERED_CUT_COPPER_IRON_BANDS).add(ModBlocks.WEATHERED_CUT_COPPER_IRON_CHEVRON).add(ModBlocks.WEATHERED_CUT_COPPER_IRON_WAVES)

                .add(ModBlocks.WAXED_WEATHERED_CUT_COPPER_AMETHYST_BANDS).add(ModBlocks.WAXED_WEATHERED_CUT_COPPER_AMETHYST_CHEVRON).add(ModBlocks.WAXED_WEATHERED_CUT_COPPER_AMETHYST_WAVES)
                .add(ModBlocks.WAXED_WEATHERED_CUT_COPPER_DIAMOND_BANDS).add(ModBlocks.WAXED_WEATHERED_CUT_COPPER_DIAMOND_CHEVRON).add(ModBlocks.WAXED_WEATHERED_CUT_COPPER_DIAMOND_WAVES)
                .add(ModBlocks.WAXED_WEATHERED_CUT_COPPER_EMERALD_BANDS).add(ModBlocks.WAXED_WEATHERED_CUT_COPPER_EMERALD_CHEVRON).add(ModBlocks.WAXED_WEATHERED_CUT_COPPER_EMERALD_WAVES)
                .add(ModBlocks.WAXED_WEATHERED_CUT_COPPER_GOLD_BANDS).add(ModBlocks.WAXED_WEATHERED_CUT_COPPER_GOLD_CHEVRON).add(ModBlocks.WAXED_WEATHERED_CUT_COPPER_GOLD_WAVES)
                .add(ModBlocks.WAXED_WEATHERED_CUT_COPPER_IRON_BANDS).add(ModBlocks.WAXED_WEATHERED_CUT_COPPER_IRON_CHEVRON).add(ModBlocks.WAXED_WEATHERED_CUT_COPPER_IRON_WAVES)

        // oxidized cut copper engraved
                .add(ModBlocks.OXIDIZED_CUT_COPPER_AMETHYST_BANDS).add(ModBlocks.OXIDIZED_CUT_COPPER_AMETHYST_CHEVRON).add(ModBlocks.OXIDIZED_CUT_COPPER_AMETHYST_WAVES)
                .add(ModBlocks.OXIDIZED_CUT_COPPER_DIAMOND_BANDS).add(ModBlocks.OXIDIZED_CUT_COPPER_DIAMOND_CHEVRON).add(ModBlocks.OXIDIZED_CUT_COPPER_DIAMOND_WAVES)
                .add(ModBlocks.OXIDIZED_CUT_COPPER_EMERALD_BANDS).add(ModBlocks.OXIDIZED_CUT_COPPER_EMERALD_CHEVRON).add(ModBlocks.OXIDIZED_CUT_COPPER_EMERALD_WAVES)
                .add(ModBlocks.OXIDIZED_CUT_COPPER_GOLD_BANDS).add(ModBlocks.OXIDIZED_CUT_COPPER_GOLD_CHEVRON).add(ModBlocks.OXIDIZED_CUT_COPPER_GOLD_WAVES)
                .add(ModBlocks.OXIDIZED_CUT_COPPER_IRON_BANDS).add(ModBlocks.OXIDIZED_CUT_COPPER_IRON_CHEVRON).add(ModBlocks.OXIDIZED_CUT_COPPER_IRON_WAVES)

                .add(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_AMETHYST_BANDS).add(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_AMETHYST_CHEVRON).add(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_AMETHYST_WAVES)
                .add(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_DIAMOND_BANDS).add(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_DIAMOND_CHEVRON).add(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_DIAMOND_WAVES)
                .add(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_EMERALD_BANDS).add(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_EMERALD_CHEVRON).add(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_EMERALD_WAVES)
                .add(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_GOLD_BANDS).add(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_GOLD_CHEVRON).add(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_GOLD_WAVES)
                .add(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_IRON_BANDS).add(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_IRON_CHEVRON).add(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_IRON_WAVES)

        // nether bricks engraved
                .add(ModBlocks.NETHER_BRICKS_GOLD_BANDS).add(ModBlocks.NETHER_BRICKS_GOLD_CHEVRON).add(ModBlocks.NETHER_BRICKS_GOLD_WAVES)
                .add(ModBlocks.NETHER_BRICKS_IRON_BANDS).add(ModBlocks.NETHER_BRICKS_IRON_CHEVRON).add(ModBlocks.NETHER_BRICKS_IRON_WAVES)

                .add(ModBlocks.NETHER_BRICKS_COPPER_BANDS).add(ModBlocks.NETHER_BRICKS_COPPER_CHEVRON).add(ModBlocks.NETHER_BRICKS_COPPER_WAVES)
                .add(ModBlocks.NETHER_BRICKS_EXPOSED_COPPER_BANDS).add(ModBlocks.NETHER_BRICKS_EXPOSED_COPPER_CHEVRON).add(ModBlocks.NETHER_BRICKS_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.NETHER_BRICKS_WEATHERED_COPPER_BANDS).add(ModBlocks.NETHER_BRICKS_WEATHERED_COPPER_CHEVRON).add(ModBlocks.NETHER_BRICKS_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.NETHER_BRICKS_OXIDIZED_COPPER_BANDS).add(ModBlocks.NETHER_BRICKS_OXIDIZED_COPPER_CHEVRON).add(ModBlocks.NETHER_BRICKS_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.NETHER_BRICKS_WAXED_COPPER_BANDS).add(ModBlocks.NETHER_BRICKS_WAXED_COPPER_CHEVRON).add(ModBlocks.NETHER_BRICKS_WAXED_COPPER_WAVES)
                .add(ModBlocks.NETHER_BRICKS_WAXED_EXPOSED_COPPER_BANDS).add(ModBlocks.NETHER_BRICKS_WAXED_EXPOSED_COPPER_CHEVRON).add(ModBlocks.NETHER_BRICKS_WAXED_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.NETHER_BRICKS_WAXED_WEATHERED_COPPER_BANDS).add(ModBlocks.NETHER_BRICKS_WAXED_WEATHERED_COPPER_CHEVRON).add(ModBlocks.NETHER_BRICKS_WAXED_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.NETHER_BRICKS_WAXED_OXIDIZED_COPPER_BANDS).add(ModBlocks.NETHER_BRICKS_WAXED_OXIDIZED_COPPER_CHEVRON).add(ModBlocks.NETHER_BRICKS_WAXED_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.NETHER_BRICKS_LAPIS_BANDS).add(ModBlocks.NETHER_BRICKS_LAPIS_CHEVRON).add(ModBlocks.NETHER_BRICKS_LAPIS_WAVES)
                .add(ModBlocks.NETHER_BRICKS_REDSTONE_BANDS).add(ModBlocks.NETHER_BRICKS_REDSTONE_CHEVRON).add(ModBlocks.NETHER_BRICKS_REDSTONE_WAVES)
                .add(ModBlocks.NETHER_BRICKS_QUARTZ_BANDS).add(ModBlocks.NETHER_BRICKS_QUARTZ_CHEVRON).add(ModBlocks.NETHER_BRICKS_QUARTZ_WAVES)
                .add(ModBlocks.NETHER_BRICKS_BLAZE_BANDS).add(ModBlocks.NETHER_BRICKS_BLAZE_CHEVRON).add(ModBlocks.NETHER_BRICKS_BLAZE_WAVES)

        // polished blackstone bricks engraved
                .add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_AMETHYST_BANDS).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_AMETHYST_CHEVRON).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_AMETHYST_WAVES)
                .add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_DIAMOND_BANDS).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_DIAMOND_CHEVRON).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_DIAMOND_WAVES)
                .add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_EMERALD_BANDS).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_EMERALD_CHEVRON).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_EMERALD_WAVES)
                .add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_GOLD_BANDS).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_GOLD_CHEVRON).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_GOLD_WAVES)
                .add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_IRON_BANDS).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_IRON_CHEVRON).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_IRON_WAVES)

                .add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_COPPER_BANDS).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_COPPER_CHEVRON).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_COPPER_WAVES)
                .add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_EXPOSED_COPPER_BANDS).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_EXPOSED_COPPER_CHEVRON).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_WEATHERED_COPPER_BANDS).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_WEATHERED_COPPER_CHEVRON).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_OXIDIZED_COPPER_BANDS).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_OXIDIZED_COPPER_CHEVRON).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_WAXED_COPPER_BANDS).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_WAXED_COPPER_CHEVRON).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_WAXED_COPPER_WAVES)
                .add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_WAXED_EXPOSED_COPPER_BANDS).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_WAXED_EXPOSED_COPPER_CHEVRON).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_WAXED_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_WAXED_WEATHERED_COPPER_BANDS).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_WAXED_WEATHERED_COPPER_CHEVRON).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_WAXED_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_WAXED_OXIDIZED_COPPER_BANDS).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_WAXED_OXIDIZED_COPPER_CHEVRON).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_WAXED_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_LAPIS_BANDS).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_LAPIS_CHEVRON).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_LAPIS_WAVES)
                .add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_REDSTONE_BANDS).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_REDSTONE_CHEVRON).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_REDSTONE_WAVES)
                .add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_QUARTZ_BANDS).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_QUARTZ_CHEVRON).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_QUARTZ_WAVES)
                .add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_BLAZE_BANDS).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_BLAZE_CHEVRON).add(ModBlocks.POLISHED_BLACKSTONE_BRICKS_BLAZE_WAVES)

        // quartz bricks engraved
                .add(ModBlocks.QUARTZ_BRICKS_AMETHYST_BANDS)
                .add(ModBlocks.QUARTZ_BRICKS_AMETHYST_CHEVRON)
                .add(ModBlocks.QUARTZ_BRICKS_AMETHYST_WAVES)
                .add(ModBlocks.QUARTZ_BRICKS_DIAMOND_BANDS)
                .add(ModBlocks.QUARTZ_BRICKS_DIAMOND_CHEVRON)
                .add(ModBlocks.QUARTZ_BRICKS_DIAMOND_WAVES)
                .add(ModBlocks.QUARTZ_BRICKS_EMERALD_BANDS)
                .add(ModBlocks.QUARTZ_BRICKS_EMERALD_CHEVRON)
                .add(ModBlocks.QUARTZ_BRICKS_EMERALD_WAVES)
                .add(ModBlocks.QUARTZ_BRICKS_GOLD_BANDS)
                .add(ModBlocks.QUARTZ_BRICKS_GOLD_CHEVRON)
                .add(ModBlocks.QUARTZ_BRICKS_GOLD_WAVES)
                .add(ModBlocks.QUARTZ_BRICKS_IRON_BANDS)
                .add(ModBlocks.QUARTZ_BRICKS_IRON_CHEVRON)
                .add(ModBlocks.QUARTZ_BRICKS_IRON_WAVES)

                .add(ModBlocks.QUARTZ_BRICKS_COPPER_BANDS)
                .add(ModBlocks.QUARTZ_BRICKS_COPPER_CHEVRON)
                .add(ModBlocks.QUARTZ_BRICKS_COPPER_WAVES)
                .add(ModBlocks.QUARTZ_BRICKS_EXPOSED_COPPER_BANDS)
                .add(ModBlocks.QUARTZ_BRICKS_EXPOSED_COPPER_CHEVRON)
                .add(ModBlocks.QUARTZ_BRICKS_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.QUARTZ_BRICKS_WEATHERED_COPPER_BANDS)
                .add(ModBlocks.QUARTZ_BRICKS_WEATHERED_COPPER_CHEVRON)
                .add(ModBlocks.QUARTZ_BRICKS_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.QUARTZ_BRICKS_OXIDIZED_COPPER_BANDS)
                .add(ModBlocks.QUARTZ_BRICKS_OXIDIZED_COPPER_CHEVRON)
                .add(ModBlocks.QUARTZ_BRICKS_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.QUARTZ_BRICKS_WAXED_COPPER_BANDS)
                .add(ModBlocks.QUARTZ_BRICKS_WAXED_COPPER_CHEVRON)
                .add(ModBlocks.QUARTZ_BRICKS_WAXED_COPPER_WAVES)
                .add(ModBlocks.QUARTZ_BRICKS_WAXED_EXPOSED_COPPER_BANDS)
                .add(ModBlocks.QUARTZ_BRICKS_WAXED_EXPOSED_COPPER_CHEVRON)
                .add(ModBlocks.QUARTZ_BRICKS_WAXED_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.QUARTZ_BRICKS_WAXED_WEATHERED_COPPER_BANDS)
                .add(ModBlocks.QUARTZ_BRICKS_WAXED_WEATHERED_COPPER_CHEVRON)
                .add(ModBlocks.QUARTZ_BRICKS_WAXED_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.QUARTZ_BRICKS_WAXED_OXIDIZED_COPPER_BANDS)
                .add(ModBlocks.QUARTZ_BRICKS_WAXED_OXIDIZED_COPPER_CHEVRON)
                .add(ModBlocks.QUARTZ_BRICKS_WAXED_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.QUARTZ_BRICKS_LAPIS_BANDS)
                .add(ModBlocks.QUARTZ_BRICKS_LAPIS_CHEVRON)
                .add(ModBlocks.QUARTZ_BRICKS_LAPIS_WAVES)
                .add(ModBlocks.QUARTZ_BRICKS_REDSTONE_BANDS)
                .add(ModBlocks.QUARTZ_BRICKS_REDSTONE_CHEVRON)
                .add(ModBlocks.QUARTZ_BRICKS_REDSTONE_WAVES)
                .add(ModBlocks.QUARTZ_BRICKS_BLAZE_BANDS)
                .add(ModBlocks.QUARTZ_BRICKS_BLAZE_CHEVRON)
                .add(ModBlocks.QUARTZ_BRICKS_BLAZE_WAVES)

        // end stone bricks engraved
                .add(ModBlocks.END_STONE_BRICKS_AMETHYST_BANDS)
                .add(ModBlocks.END_STONE_BRICKS_AMETHYST_CHEVRON)
                .add(ModBlocks.END_STONE_BRICKS_AMETHYST_WAVES)
                .add(ModBlocks.END_STONE_BRICKS_DIAMOND_BANDS)
                .add(ModBlocks.END_STONE_BRICKS_DIAMOND_CHEVRON)
                .add(ModBlocks.END_STONE_BRICKS_DIAMOND_WAVES)
                .add(ModBlocks.END_STONE_BRICKS_EMERALD_BANDS)
                .add(ModBlocks.END_STONE_BRICKS_EMERALD_CHEVRON)
                .add(ModBlocks.END_STONE_BRICKS_EMERALD_WAVES)
                .add(ModBlocks.END_STONE_BRICKS_GOLD_BANDS)
                .add(ModBlocks.END_STONE_BRICKS_GOLD_CHEVRON)
                .add(ModBlocks.END_STONE_BRICKS_GOLD_WAVES)
                .add(ModBlocks.END_STONE_BRICKS_IRON_BANDS)
                .add(ModBlocks.END_STONE_BRICKS_IRON_CHEVRON)
                .add(ModBlocks.END_STONE_BRICKS_IRON_WAVES)

                .add(ModBlocks.END_STONE_BRICKS_COPPER_BANDS)
                .add(ModBlocks.END_STONE_BRICKS_COPPER_CHEVRON)
                .add(ModBlocks.END_STONE_BRICKS_COPPER_WAVES)
                .add(ModBlocks.END_STONE_BRICKS_EXPOSED_COPPER_BANDS)
                .add(ModBlocks.END_STONE_BRICKS_EXPOSED_COPPER_CHEVRON)
                .add(ModBlocks.END_STONE_BRICKS_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.END_STONE_BRICKS_WEATHERED_COPPER_BANDS)
                .add(ModBlocks.END_STONE_BRICKS_WEATHERED_COPPER_CHEVRON)
                .add(ModBlocks.END_STONE_BRICKS_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.END_STONE_BRICKS_OXIDIZED_COPPER_BANDS)
                .add(ModBlocks.END_STONE_BRICKS_OXIDIZED_COPPER_CHEVRON)
                .add(ModBlocks.END_STONE_BRICKS_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.END_STONE_BRICKS_WAXED_COPPER_BANDS)
                .add(ModBlocks.END_STONE_BRICKS_WAXED_COPPER_CHEVRON)
                .add(ModBlocks.END_STONE_BRICKS_WAXED_COPPER_WAVES)
                .add(ModBlocks.END_STONE_BRICKS_WAXED_EXPOSED_COPPER_BANDS)
                .add(ModBlocks.END_STONE_BRICKS_WAXED_EXPOSED_COPPER_CHEVRON)
                .add(ModBlocks.END_STONE_BRICKS_WAXED_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.END_STONE_BRICKS_WAXED_WEATHERED_COPPER_BANDS)
                .add(ModBlocks.END_STONE_BRICKS_WAXED_WEATHERED_COPPER_CHEVRON)
                .add(ModBlocks.END_STONE_BRICKS_WAXED_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.END_STONE_BRICKS_WAXED_OXIDIZED_COPPER_BANDS)
                .add(ModBlocks.END_STONE_BRICKS_WAXED_OXIDIZED_COPPER_CHEVRON)
                .add(ModBlocks.END_STONE_BRICKS_WAXED_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.END_STONE_BRICKS_LAPIS_BANDS)
                .add(ModBlocks.END_STONE_BRICKS_LAPIS_CHEVRON)
                .add(ModBlocks.END_STONE_BRICKS_LAPIS_WAVES)
                .add(ModBlocks.END_STONE_BRICKS_REDSTONE_BANDS)
                .add(ModBlocks.END_STONE_BRICKS_REDSTONE_CHEVRON)
                .add(ModBlocks.END_STONE_BRICKS_REDSTONE_WAVES)
                .add(ModBlocks.END_STONE_BRICKS_QUARTZ_BANDS)
                .add(ModBlocks.END_STONE_BRICKS_QUARTZ_CHEVRON)
                .add(ModBlocks.END_STONE_BRICKS_QUARTZ_WAVES)
                .add(ModBlocks.END_STONE_BRICKS_ENDER_BANDS)
                .add(ModBlocks.END_STONE_BRICKS_ENDER_CHEVRON)
                .add(ModBlocks.END_STONE_BRICKS_ENDER_WAVES)

        // purpur blocks engraved
                .add(ModBlocks.PURPUR_BLOCK_AMETHYST_BANDS)
                .add(ModBlocks.PURPUR_BLOCK_AMETHYST_CHEVRON)
                .add(ModBlocks.PURPUR_BLOCK_AMETHYST_WAVES)
                .add(ModBlocks.PURPUR_BLOCK_DIAMOND_BANDS)
                .add(ModBlocks.PURPUR_BLOCK_DIAMOND_CHEVRON)
                .add(ModBlocks.PURPUR_BLOCK_DIAMOND_WAVES)
                .add(ModBlocks.PURPUR_BLOCK_EMERALD_BANDS)
                .add(ModBlocks.PURPUR_BLOCK_EMERALD_CHEVRON)
                .add(ModBlocks.PURPUR_BLOCK_EMERALD_WAVES)
                .add(ModBlocks.PURPUR_BLOCK_GOLD_BANDS)
                .add(ModBlocks.PURPUR_BLOCK_GOLD_CHEVRON)
                .add(ModBlocks.PURPUR_BLOCK_GOLD_WAVES)
                .add(ModBlocks.PURPUR_BLOCK_IRON_BANDS)
                .add(ModBlocks.PURPUR_BLOCK_IRON_CHEVRON)
                .add(ModBlocks.PURPUR_BLOCK_IRON_WAVES)

                .add(ModBlocks.PURPUR_BLOCK_COPPER_BANDS)
                .add(ModBlocks.PURPUR_BLOCK_COPPER_CHEVRON)
                .add(ModBlocks.PURPUR_BLOCK_COPPER_WAVES)
                .add(ModBlocks.PURPUR_BLOCK_EXPOSED_COPPER_BANDS)
                .add(ModBlocks.PURPUR_BLOCK_EXPOSED_COPPER_CHEVRON)
                .add(ModBlocks.PURPUR_BLOCK_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.PURPUR_BLOCK_WEATHERED_COPPER_BANDS)
                .add(ModBlocks.PURPUR_BLOCK_WEATHERED_COPPER_CHEVRON)
                .add(ModBlocks.PURPUR_BLOCK_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.PURPUR_BLOCK_OXIDIZED_COPPER_BANDS)
                .add(ModBlocks.PURPUR_BLOCK_OXIDIZED_COPPER_CHEVRON)
                .add(ModBlocks.PURPUR_BLOCK_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.PURPUR_BLOCK_WAXED_COPPER_BANDS)
                .add(ModBlocks.PURPUR_BLOCK_WAXED_COPPER_CHEVRON)
                .add(ModBlocks.PURPUR_BLOCK_WAXED_COPPER_WAVES)
                .add(ModBlocks.PURPUR_BLOCK_WAXED_EXPOSED_COPPER_BANDS)
                .add(ModBlocks.PURPUR_BLOCK_WAXED_EXPOSED_COPPER_CHEVRON)
                .add(ModBlocks.PURPUR_BLOCK_WAXED_EXPOSED_COPPER_WAVES)
                .add(ModBlocks.PURPUR_BLOCK_WAXED_WEATHERED_COPPER_BANDS)
                .add(ModBlocks.PURPUR_BLOCK_WAXED_WEATHERED_COPPER_CHEVRON)
                .add(ModBlocks.PURPUR_BLOCK_WAXED_WEATHERED_COPPER_WAVES)
                .add(ModBlocks.PURPUR_BLOCK_WAXED_OXIDIZED_COPPER_BANDS)
                .add(ModBlocks.PURPUR_BLOCK_WAXED_OXIDIZED_COPPER_CHEVRON)
                .add(ModBlocks.PURPUR_BLOCK_WAXED_OXIDIZED_COPPER_WAVES)

                .add(ModBlocks.PURPUR_BLOCK_LAPIS_BANDS)
                .add(ModBlocks.PURPUR_BLOCK_LAPIS_CHEVRON)
                .add(ModBlocks.PURPUR_BLOCK_LAPIS_WAVES)
                .add(ModBlocks.PURPUR_BLOCK_REDSTONE_BANDS)
                .add(ModBlocks.PURPUR_BLOCK_REDSTONE_CHEVRON)
                .add(ModBlocks.PURPUR_BLOCK_REDSTONE_WAVES)
                .add(ModBlocks.PURPUR_BLOCK_QUARTZ_BANDS)
                .add(ModBlocks.PURPUR_BLOCK_QUARTZ_CHEVRON)
                .add(ModBlocks.PURPUR_BLOCK_QUARTZ_WAVES)
                .add(ModBlocks.PURPUR_BLOCK_ENDER_BANDS)
                .add(ModBlocks.PURPUR_BLOCK_ENDER_CHEVRON)
                .add(ModBlocks.PURPUR_BLOCK_ENDER_WAVES)

        // concrete diamond blocks
        // black concrete diamond
                .add(ModBlocks.BLACK_CONCRETE_BLUE_DIAMOND)
                .add(ModBlocks.BLACK_CONCRETE_GREEN_DIAMOND)
                .add(ModBlocks.BLACK_CONCRETE_ORANGE_DIAMOND)
                .add(ModBlocks.BLACK_CONCRETE_PURPLE_DIAMOND)
                .add(ModBlocks.BLACK_CONCRETE_RED_DIAMOND)
                .add(ModBlocks.BLACK_CONCRETE_WHITE_DIAMOND)
                .add(ModBlocks.BLACK_CONCRETE_YELLOW_DIAMOND)
        // blue concrete diamond
                .add(ModBlocks.BLUE_CONCRETE_BLACK_DIAMOND)
                .add(ModBlocks.BLUE_CONCRETE_GREEN_DIAMOND)
                .add(ModBlocks.BLUE_CONCRETE_ORANGE_DIAMOND)
                .add(ModBlocks.BLUE_CONCRETE_PURPLE_DIAMOND)
                .add(ModBlocks.BLUE_CONCRETE_RED_DIAMOND)
                .add(ModBlocks.BLUE_CONCRETE_WHITE_DIAMOND)
                .add(ModBlocks.BLUE_CONCRETE_YELLOW_DIAMOND)
        // green concrete diamond
                .add(ModBlocks.GREEN_CONCRETE_BLUE_DIAMOND)
                .add(ModBlocks.GREEN_CONCRETE_BLACK_DIAMOND)
                .add(ModBlocks.GREEN_CONCRETE_ORANGE_DIAMOND)
                .add(ModBlocks.GREEN_CONCRETE_PURPLE_DIAMOND)
                .add(ModBlocks.GREEN_CONCRETE_RED_DIAMOND)
                .add(ModBlocks.GREEN_CONCRETE_WHITE_DIAMOND)
                .add(ModBlocks.GREEN_CONCRETE_YELLOW_DIAMOND)
        // orange concrete diamond
                .add(ModBlocks.ORANGE_CONCRETE_BLUE_DIAMOND)
                .add(ModBlocks.ORANGE_CONCRETE_GREEN_DIAMOND)
                .add(ModBlocks.ORANGE_CONCRETE_BLACK_DIAMOND)
                .add(ModBlocks.ORANGE_CONCRETE_PURPLE_DIAMOND)
                .add(ModBlocks.ORANGE_CONCRETE_RED_DIAMOND)
                .add(ModBlocks.ORANGE_CONCRETE_WHITE_DIAMOND)
                .add(ModBlocks.ORANGE_CONCRETE_YELLOW_DIAMOND)
        // purple concrete diamond
                .add(ModBlocks.PURPLE_CONCRETE_BLUE_DIAMOND)
                .add(ModBlocks.PURPLE_CONCRETE_GREEN_DIAMOND)
                .add(ModBlocks.PURPLE_CONCRETE_ORANGE_DIAMOND)
                .add(ModBlocks.PURPLE_CONCRETE_BLACK_DIAMOND)
                .add(ModBlocks.PURPLE_CONCRETE_RED_DIAMOND)
                .add(ModBlocks.PURPLE_CONCRETE_WHITE_DIAMOND)
                .add(ModBlocks.PURPLE_CONCRETE_YELLOW_DIAMOND)
        // red concrete diamond
                .add(ModBlocks.RED_CONCRETE_BLUE_DIAMOND)
                .add(ModBlocks.RED_CONCRETE_GREEN_DIAMOND)
                .add(ModBlocks.RED_CONCRETE_ORANGE_DIAMOND)
                .add(ModBlocks.RED_CONCRETE_PURPLE_DIAMOND)
                .add(ModBlocks.RED_CONCRETE_BLACK_DIAMOND)
                .add(ModBlocks.RED_CONCRETE_WHITE_DIAMOND)
                .add(ModBlocks.RED_CONCRETE_YELLOW_DIAMOND)
        // yellow concrete diamond
                .add(ModBlocks.YELLOW_CONCRETE_BLUE_DIAMOND)
                .add(ModBlocks.YELLOW_CONCRETE_GREEN_DIAMOND)
                .add(ModBlocks.YELLOW_CONCRETE_ORANGE_DIAMOND)
                .add(ModBlocks.YELLOW_CONCRETE_PURPLE_DIAMOND)
                .add(ModBlocks.YELLOW_CONCRETE_RED_DIAMOND)
                .add(ModBlocks.YELLOW_CONCRETE_WHITE_DIAMOND)
                .add(ModBlocks.YELLOW_CONCRETE_BLACK_DIAMOND)
        // white concrete diamond
                .add(ModBlocks.WHITE_CONCRETE_BLUE_DIAMOND)
                .add(ModBlocks.WHITE_CONCRETE_GREEN_DIAMOND)
                .add(ModBlocks.WHITE_CONCRETE_ORANGE_DIAMOND)
                .add(ModBlocks.WHITE_CONCRETE_PURPLE_DIAMOND)
                .add(ModBlocks.WHITE_CONCRETE_RED_DIAMOND)
                .add(ModBlocks.WHITE_CONCRETE_BLACK_DIAMOND)
                .add(ModBlocks.WHITE_CONCRETE_YELLOW_DIAMOND)
                .add(ModBlocks.WHITE_CONCRETE_LIGHT_BLUE_DIAMOND)
                .add(ModBlocks.WHITE_CONCRETE_LIME_DIAMOND)
                .add(ModBlocks.WHITE_CONCRETE_MAGENTA_DIAMOND)
        // light blue concrete diamond
                .add(ModBlocks.LIGHT_BLUE_CONCRETE_WHITE_DIAMOND)
                .add(ModBlocks.LIGHT_BLUE_CONCRETE_LIME_DIAMOND)
                .add(ModBlocks.LIGHT_BLUE_CONCRETE_MAGENTA_DIAMOND)
        // light blue concrete diamond
                .add(ModBlocks.LIME_CONCRETE_LIGHT_BLUE_DIAMOND)
                .add(ModBlocks.LIME_CONCRETE_WHITE_DIAMOND)
                .add(ModBlocks.LIME_CONCRETE_MAGENTA_DIAMOND)
        // light blue concrete diamond
                .add(ModBlocks.MAGENTA_CONCRETE_LIGHT_BLUE_DIAMOND)
                .add(ModBlocks.MAGENTA_CONCRETE_LIME_DIAMOND)
                .add(ModBlocks.MAGENTA_CONCRETE_WHITE_DIAMOND)


        // light blue concrete diamond
                .add(ModBlocks.NIGHT_SKY_BLOCK)
                .add(ModBlocks.MOVING_NIGHT_SKY_BLOCK)
                .add(ModBlocks.CINEMATIC_STONE_BRICKS)


        ;

        getOrCreateTagBuilder(BlockTags.NEEDS_IRON_TOOL);
        getOrCreateTagBuilder(BlockTags.AXE_MINEABLE);

    }
}
